# Site settings
title: Flora on Fauna
email: freyja@fehuleather.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures in leather with flowers and friends.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fulveland.github.io" # the base hostname & protocol for your site
twitter_username: fehuleather
permalink: ":title.html"

# Build settings
markdown: kramdown
